[project]
name = "rag"
version = "0.1.0"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 67.6"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
rag = "rag.cli:cli"
